Fixes #2465 - Simplify/Enforce LayoutStyle.Absolute when X, Y, Width, and/or Height are null or Absolute()
gui-cs/Terminal.Gui pull request #2467
Opened 2023-03-30 02:46 UTC by tig

Fixes #2465

Draft just to get thinking going. Nothing really working yet. See unit tests I've added though.

2023-04-05 11:28 UTC, BDisp requested changes

2023-04-05 11:28 UTC, BDisp commented on Terminal.Gui/Core/View.cs
> +				Height = frame.Height;
You are forcing the Pos/Dim to be `Absolute` even they aren't. So, in my opinion the `Frame` setter mustn't set the Pos/Dim values.

2023-04-05 11:28 UTC, BDisp commented on Terminal.Gui/Core/View.cs
> +					if (Height == null) Height = Frame.Height;
Can be replaced by:
```cs
X ??= Frame.X;
Y ??= Frame.Y;
Width ??= Frame.Width;
Height ??= Frame.Height;
```
Additionally in each` Pos/Dim (X, Y, Width, Height)` setter you after must update the `_layoutStyle` field by get the `LayoutStyle` value:
`
_layoutStyle = LayoutStyle;
`

2024-01-03 20:11 UTC, tig commented
@BDisp and @tznind - I've finally come back to this PR and:

- [x] Merged with v2_develop
- [x] Updated API docs to be more complete and accurate
- [x] Fixed all Views that were using `Bounds` or calling `LayoutSubViews` before `IsInitalized`
- [x] Fixed a few other things (esp in ComboBox) that needed fixing

What I *didn't* do:

- [ ] Actually enforce LayoutStyle as was originally proposed here. I'd love your thoughts on that now.

Please review asap. Thanks!

2024-01-03 20:38 UTC, BDisp commented
Something is wrong with `All Views Tester`. It starting at (0,0) but navigate down and then up the views don't start at (0,0).

2024-01-03 21:04 UTC, tig commented
> Something is wrong with `All Views Tester`. It starting at (0,0) but navigate down and then up the views don't start at (0,0).

Ah, with mouse. With keyboard it's fine. On it...

2024-01-03 21:11 UTC, BDisp commented
> > Something is wrong with `All Views Tester`. It starting at (0,0) but navigate down and then up the views don't start at (0,0).
> 
> Ah, with mouse. With keyboard it's fine. On it...

With the keyboard. Navigate downward until `Dialog` and then navigate upward and you will see that the views aren't at (0,0) anymore.

2024-01-03 21:28 UTC, tig commented
> > > Something is wrong with `All Views Tester`. It starting at (0,0) but navigate down and then up the views don't start at (0,0).
> > 
> > 
> > Ah, with mouse. With keyboard it's fine. On it...
> 
> With the keyboard. Navigate downward until `Dialog` and then navigate upward and you will see that the views aren't at (0,0) anymore.
> 
> **Edit:** `Dialog` is centered horizontal and vertical and thus it seems the upper left coordinate is changed for all views.

Fixed.

2024-01-03 21:38 UTC, BDisp commented
Some of the views aren't show, like the `TextField`.

2024-01-03 22:13 UTC, tig commented
> Some of the views aren't show, like the `TextField`.

Fixed. ;-)

2024-01-04 16:45 UTC, tig commented
@BDisp I'd like to merge this so it can be picked up in https://github.com/gui-cs/Terminal.Gui/pull/3078 and https://github.com/BDisp/Terminal.Gui/pull/172 so I can more easily debug (this PR removes a ton of debug spew).

Are you good with my changes here?

2024-01-04 17:34 UTC, BDisp commented
Done @tig. Thanks.

2024-01-04 17:40 UTC, merged