Fixes #2793. Windows Terminal still show vertical scroll bar using WindowsDriver.
gui-cs/Terminal.Gui pull request #2794
Opened 2023-08-09 00:13 UTC by BDisp

Fixes #2793 - Since WT doesn't allows resizing the buffer using Win32 API, we need to use the `"\x1b[3J"` escape sequence. This issue only happens running `WindowsDriver` on `Windows Terminal`. @tig please reconsider this because we mustn't allow WT breaking the back buffer because the scroll bar is enabled after resizing. With all others drivers this issue doesn't happens on WT.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

2023-08-13 15:59 UTC, tig commented
I think this finally fixes things!

Can you please address my review comment?

2023-08-13 18:06 UTC, BDisp commented
> I think this finally fixes things!
> 
I also think so.

> Can you please address my review comment?

@tig I don't see any review comment of your. Where it's?

2023-08-14 14:54 UTC, tig commented
> > I think this finally fixes things!
> 
> I also think so.
> 
> > Can you please address my review comment?
> 
> @tig I don't see any review comment of your. Where it's?

<img width="456" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/dc9a393d-5ef3-4cdc-906d-16c87a6d171a">

2023-08-14 15:24 UTC, BDisp commented
@tig but do you know why I'm not seeing the reviews that is in the image in this PR?

2023-08-14 15:59 UTC, tig requested changes

2023-08-14 15:59 UTC, tig commented
Maybe I didn't submit correctly? I just tried again.

2023-08-14 17:34 UTC, BDisp commented on Terminal.Gui/ConsoleDrivers/WindowsDriver.cs
> +		private static string GetParentProcessName ()
> This returns `devenv` when running in debugger.

Yes I know and that why I created a new profile `UICatalog WT` to run the app on the `Windows Terminal`. The disadvantage of this is that we need to attach to the VS2022 for debugging.

> Much better solution:
> 
> _isWindowsTerminal = Environment.GetEnvironmentVariable ("WT_SESSION") != null;

Yes I agree and I'll use it but it also returns false when running in debugger on VS2022. It only return true if I use the new profile or running from the Windows Terminal. Do you have any configuration that return true directly from the VS2022 debugger?

2023-08-14 19:23 UTC, BDisp commented on Terminal.Gui/Core/Border.cs
> +			if (borderBrush != null) {
Done with #2807.

2023-08-14 19:25 UTC, BDisp commented on Terminal.Gui/ConsoleDrivers/WindowsDriver.cs
> +		private static string GetParentProcessName ()
Done with https://github.com/gui-cs/Terminal.Gui/pull/2794/commits/b607280e09cd3d659df6207e368580ab9c557988.
But `isWindowsTerminal` returns false even the Windows Terminal is the default terminal, debugging from VS2022.

2023-08-14 19:30 UTC, BDisp commented
For me the `isWindowsTerminal` only returns `true` if I run from the `UICatalog WT` profile or running from a `Windows Terminal`. Both I have to attach to the VS2022 if I want to debug.

2023-08-14 20:59 UTC, BDisp commented
Thinking better, to really test if this PR does the job we want is better running on an open terminal to see the behavior after exit the app. If it's through VS2022 debugger we will not see that behavior. Run with different terminals.

2023-08-14 22:10 UTC, tig commented
> Thinking better, to really test if this PR does the job we want is better running on an open terminal to see the behavior after exit the app. If it's through VS2022 debugger we will not see that behavior. Run with different terminals.

I agree. This is how I do my testing.

2023-08-14 22:11 UTC, tig approved these changes

2023-08-14 22:11 UTC, merged

2023-08-14 22:16 UTC, BDisp commented
> I agree. This is how I do my testing.

@tig can you use the mouse on ConEmu? I don't know if there is some setting.