Fixes #3317. Listvew mouse event doesn't cause a SelectedItemChanged event to fire
gui-cs/Terminal.Gui pull request #3321
Opened 2024-03-13 21:23 UTC by BDisp

## Fixes

- Fixes #3317

## Proposed Changes/Todos

- [x] Also fire event if `AllowsMarking` is `true` on click
- [x] Added unit test for proof

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

2024-03-14 03:26 UTC, dodexahedron requested changes
Just one minor nitpick on terminology

2024-03-14 03:26 UTC, dodexahedron commented on UnitTests/Views/ListViewTests.cs
> +		public void SelectedItemChanged_Event_Is_Also_Fired_With_AllowsMarking_True_By_Keyboard_Or_Mouse ()
Very minor nitpick for consistency with the stack: The dotnet/c# term for events is "raise," not "fire."

2024-03-14 15:05 UTC, tig approved these changes

2024-03-16 15:39 UTC, tig approved these changes

2024-03-16 15:39 UTC, merged