Fixes #3037. Adds `Bar` & `Shortcut`
gui-cs/Terminal.Gui pull request #3533
Opened 2024-06-10 01:57 UTC by tig

## Fixes

- Fixes #3037

## Proposed Changes/Todos

- [ ] Todo 1

## Pull Request checklist:

- [ ] I've named my PR in the form of "Fixes #issue. Terse description."
- [ ] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [ ] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [ ] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any poor grammar or misspellings
- [ ] I conducted basic QA to assure all features are working

2024-06-13 19:17 UTC, tig commented
Tons of progress on this.

It is now at the point that replacing `StatusBar` will be trivial. I already updated UI Catalog to use `Bar` instead of `StatusBar`.

`Menu` and `MenuBar` will require a lot more work, but directionally I'm very happy.

![Uploading 7QxcJMo[1].gif…]()

2024-06-17 13:57 UTC, tig commented
I'll add more unit tests before merging, and may spend more time on ensuring this theoretically can replace `Menu` and `MenuBar`, but this is ready for review.

2024-06-17 20:19 UTC, tig commented
Related question:

In v1 and early v2, for a Hotkey (e.g. "I'm a _Label") to get invoked, the view in question had to be a subview of Top.Focused. And only subviews of Top.Focused were considered.

This mean that even though a hotkey was defined, the view heirarchy might prevent it from working. You could see this in All Views Tester where the size and position FrameViews have subviews with hotkeys. You could only use keyboard to navigate to a view in the OTHER FrameView by tabbing to it first. 

In this PR, I've changed this such that as long as the view is visible (and enabled), the hotkey will cause it to gain focus. I think this is far more natural and sensical.

2024-06-17 20:36 UTC, BDisp commented
I also think that all shortcuts predefined by `Application` should be unique. If the user configures an identical shortcut, it will be ignored and the default one defined by the application will be executed. I'm tired of facing this situation with `Windows Terminal`, so be patient.
In the remaining shortcuts, priority should be `Focused`, `SuperView`, `Application`.

> In this PR, I've changed this such that as long as the view is visible (and enabled), the hotkey will cause it to gain focus. I think this is far more natural and sensical.

You are referring to whether `CanFocus` is also true, right?

2024-06-17 22:25 UTC, tig commented
> You are referring to whether `CanFocus` is also true, right?

Not entirely. E.g. `Label` is `CanFocus = false`, but the whole point of `Label` is to act as a hotkey for the View it is a label for.

Above, you used the term shortcut. I'd appreciate it if you re-wrote what you used using this terminology (or, if the terminology doesn't make sense, suggest how it could be improved):

### **[HotKey](~/api/Terminal.Gui.View.yml#Terminal_Gui_View_HotKey)** 

A **HotKey** is a keypress that selects a visible UI item. For selecting items across `View`s (e.g. a `Button` in a `Dialog`) the keypress must have the `Alt` modifier. For selecting items within a `View` that are not `View`s themselves, the keypress can be key without the `Alt` modifier.  For example, in a `Dialog`, a `Button` with the text of "_Text" can be selected with `Alt-T`. Or, in a `Menu` with "_File _Edit", `Alt-F` will select (show) the "_File" menu. If the "_File" menu has a sub-menu of "_New" `Alt-N` or `N` will ONLY select the "_New" sub-menu if the "_File" menu is already opened.

By default, the `Text` of a `View` is used to determine the `HotKey` by looking for the first occurrence of the [HotKeySpecifier](~/api/Terminal.Gui.View.yml#Terminal_Gui_View_HotKeySpecifier) (which is underscore (`_`) by default). The character following the underscore is the `HotKey`. If the `HotKeySpecifier` is not found in `Text`, the first character of `Text` is used as the `HotKey`. The `Text` of a `View` can be changed at runtime, and the `HotKey` will be updated accordingly. [HotKey](~/api/Terminal.Gui.View.yml#Terminal_Gui_View_HotKey) is `virtual` enabling this behavior to be customized.

### **[Shortcut](~/api/Terminal.Gui.Shortcut.yml) - An opinionated (visually & API) View for displaying a command, helptext, key.
**

A **Shortcut** is a keypress that invokes a [Command](~/api/Terminal.Gui.Command.yml) or `View`-defined action even if the `View` that defines them is not focused or visible (but the `View` must be enabled). Shortcuts can be any keypress; `Key.A`, `Key.A | Key.Ctrl`, `Key.A | Key.Ctrl | Key.Alt`, `Key.Del`, and `Key.F1`, are all valid. 

`Shortcuts` are used to define application-wide actions (e.g. `Quit`), or actions that are not visible (e.g. `Copy`).

[MenuBar](~/api/Terminal.Gui.MenuBar.yml), [ContextMenu](~/api/Terminal.Gui.ContextMenu.yml), and [StatusBar](~/api/Terminal.Gui.StatusBar.yml) support `Shortcut`s.

2024-06-17 22:39 UTC, tig commented
@bidisp - Do you know if there's way to "Un focus" a view? There are times where I'd like to say "Make it so NO view in this View heirarchy has focus".

2024-06-17 22:58 UTC, BDisp commented
> @bidisp - Do you know if there's way to "Un focus" a view? There are times where I'd like to say "Make it so NO view in this View heirarchy has focus".

If it is internally you can use `SuperView.Focused = null`.

2024-06-18 21:18 UTC, BDisp requested changes
LGTM. Only 3 items need your attention.

2024-06-18 21:18 UTC, BDisp commented on UICatalog/Scenarios/HexEditor.cs
> +        Toplevel app = new Toplevel ()
Please add `Application.Init ();` into the scenario to avoid exception been throwing.

2024-06-18 21:18 UTC, BDisp commented on UICatalog/Scenarios/InteractiveTree.cs
> +        var appWindow = new Toplevel ()
Please add `Application.Init ();` into the scenario to avoid exception been throwing.

2024-06-18 21:18 UTC, BDisp commented on UICatalog/Scenarios/LineViewExample.cs
> +        Toplevel appWindow = new ();
Please add `Application.Init ();` into the scenario to avoid exception been throwing.

2024-06-19 00:15 UTC, dodexahedron approved these changes
Very minor nit picks.

But I gotta go, so I'm sending this your way.

2024-06-19 00:15 UTC, dodexahedron commented on UICatalog/Scenarios/InteractiveTree.cs
> +        appWindow.Dispose ();
Note that calls to Dispose that are not within a `finally` block (either explicitly or via a `using`) will never get called if there's an unhandled exception.

Probably good to encourage proper disposal in the samples, but of course it's not a big deal. 🤷‍♂️

2024-06-19 00:15 UTC, dodexahedron commented on Terminal.Gui/ConsoleDrivers/CursesDriver/constants.cs
It sure will be nice if/when Curses can DIAF.

2024-06-19 00:15 UTC, dodexahedron commented on Terminal.Gui/ConsoleDrivers/EscSeqUtils/EscSeqUtils.cs
> +                key = GetConsoleKey (terminator [0], values [0], ref mod, ref keyChar);
I don't love this.

Once there start being multiple outs or non-readonly refs, it's usually time to either use an implicit ValueTuple or a formal return type. Considering the scope of these, this is actually potentially a place where a ref struct could be quite beneficial.

Not worth upending that right now though. Just a note.

2024-06-19 00:15 UTC, dodexahedron commented on Terminal.Gui/ConsoleDrivers/EscSeqUtils/EscSeqUtils.cs
> +        if (terminator == 'l')
These could be rolled into the switch as guard clauses for consistency.

2024-06-19 00:15 UTC, dodexahedron commented on Terminal.Gui/Drawing/Aligner.cs
> +        AlignmentModes mode = alignmentMode & ~AlignmentModes.AddSpaceBetweenItems; // copy to avoid modifying the original
🙏 

Did you profile this? I have. This makes a surprisingly significant difference (a good one).

Thank you!

2024-06-19 11:31 UTC, BDisp commented
@tig some unit tests are failing. I think what causes this are the changes in ScenarioTests in which you call `Application.RemoveTimeout` when other processes may be occurring in other threads. This manipulation will have to be carried out with thread safety, otherwise it will happen that when `Application.QuitKey` is called it will throw an exception

```ex
System.NullReferenceException: 'Object reference not set to an instance of an object.'

scenario was null.
```

I recommend reverting these changes or ensuring that they are made thread-safe.

By the way, have you already merged this branch with the v2_develop branch (updated, of course)? I check that there are commits that are already included in v2_develop but appear in this PR as new commits.

2024-06-19 18:38 UTC, tig commented
> @tig some unit tests are failing...  or ensuring that they are made thread-safe.

Yeah, I was not quite done with making those changes. I was throwing spaghetti a the wall to see what would stick and then had to go to bed. I've now thought it through better and think it is now correct.

Please take a look now and let me know if you agree or not.

2024-06-19 22:29 UTC, BDisp commented
Unit tests passed on Windows but not on Linux. Are these changes made really necessary?

2024-06-20 14:12 UTC, tig commented
> Unit tests passed on Windows but not on Linux. Are these changes made really necessary?

Here's why:

- I had test failures that were really hard to track down because the scenario tests were failing when unrelated. This makes those scenario tests more robust and less likely to cause other tests to fail.
- Sample code should illustrate correctness. Having a test that proves each `Scenario` calls Init/Shutdown correctly enforces this.
- That code was poorly written originally (by me) and was incorrect. It had a high probability of failing in the future in weird ways.

2024-06-20 14:44 UTC, BDisp commented
> Here's why:
> 
> * I had test failures that were really hard to track down because the scenario tests were failing when unrelated. This makes those scenario tests more robust and less likely to cause other tests to fail.

Yes, this could actually be happening when `Application.Init` is called and there are processes running in the background that are using `Terminal.Gui`, namely the `SynchronizationContext` which, being forced to close, will throw an exception, as is expected when it is returned from the respective process.

> * Sample code should illustrate correctness. Having a test that proves each `Scenario` calls Init/Shutdown correctly enforces this.

Because of possible background processes, it is not enough to ensure that Init/Shutdown are in sync. It is also necessary to check if there are still processes running in the background and wait for them to complete before being destroyed by Shutdown.

> * That code was poorly written originally (by me) and was incorrect. It had a high probability of failing in the future in weird ways.

It wasn't poorly written by you, on the contrary. What happens is that `Terminal.Gui` is always evolving and it is impossible to predict future impacts. So we have to have something that checks the state of `Mainloop.IdleHandlers` and waits for its completion before discarding all objects in Shutdown.

2024-06-20 17:14 UTC, tig commented
I'm trying to debug the linux unit test failure. This new test passes on Windows but never exits when run on Linux.

Stumped.

```cs
    [Fact]
    public void Run_Iteration_Fires ()
    {
        int iteration = 0;

        Application.Init ();

        Application.Iteration += Application_Iteration;
        Application.Run<Toplevel> ().Dispose ();

        Assert.Equal (1, iteration);
        Application.Shutdown ();

        return;

        void Application_Iteration (object sender, IterationEventArgs e)
        {
            iteration++;
            Application.RequestStop ();
        }
    }
```

2024-06-20 17:34 UTC, tig commented
To be clear, the `Iteration` event is never fired on Linux with this test.

2024-06-20 17:40 UTC, tig commented
I am calling `Init` without a driver. Hence on Windows, WindowsDriver is being used. 

If I change to `Init(new FakeDriver())` this test succeeds on both Windows and Linux.

Oops.

2024-06-20 17:40 UTC, BDisp commented
> I'm trying to debug the linux unit test failure. This new test passes on Windows but never exits when run on Linux.

The application doesn't even end in WindowsDriver.

> To be clear, the `Iteration` event is never fired on Linux with this test.

Not even in WindowsDriver.

2024-06-20 17:44 UTC, BDisp commented
So perhaps the failure in the unit tests could be something that could be using the `WindowsDriver` or the `CursesDriver` ending up giving an error.

2024-06-20 21:19 UTC, BDisp commented
`AutoInitShutdown` can be removed here because the `Application.Init` is called in the NavigationTests.cs.

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/d7adaf78-1a59-41c4-8542-ab122b45272e)

2024-06-20 21:19 UTC, BDisp approved these changes

2024-06-20 21:52 UTC, merged