V2 drivers
gui-cs/Terminal.Gui pull request #3837
Opened 2024-11-19 21:46 UTC by tznind

## Fixes

- Fixes #_____

## Proposed Changes/Todos

- [ ] Todo 1

## Pull Request checklist:

- [ ] I've named my PR in the form of "Fixes #issue. Terse description."
- [ ] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [ ] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [ ] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any poor grammar or misspellings
- [ ] I conducted basic QA to assure all features are working

2024-11-23 15:11 UTC, tig commented
Hope you're ok with me updating the title & first post...

2024-11-23 17:00 UTC, tznind commented
> Hope you're ok with me updating the title & first post...

No problem! Always appreciate a clear naming

Now we have fledgling support for
- Keyboard
- Mouse
- Screen size

Net (i.e. native dotnet) and Windows (i.e win 32 api) are the two implementations - I assume we can drop curses?

![resize-etc](https://github.com/user-attachments/assets/925ea4f6-a63c-4da3-a9a4-86597a4fa74f)

2024-11-25 20:54 UTC, tznind commented
Working on it but I think this is how I want to handle mouse.  It needs work but goal is to capture all the relevant info as you would on desktop and only release events when sure of end users behaviour:

This would all be internal to the state machines initially and may just surface with the existing API until our events system aligns.

```csharp
#nullable enable

namespace Terminal.Gui;

public class MouseStateManager
{
    /// <summary>
    /// Function for returning the current time. Use in unit tests to
    /// ensure repeatable tests.
    /// </summary>
    private Func<DateTime> Now { get; set; }

    /// <summary>
    /// How long to wait for a second click after the first before giving up and
    /// releasing event as a 'click'
    /// </summary>
    public TimeSpan DoubleClickThreshold { get; set; }

    /// <summary>
    /// How long to wait for a third click after the second before giving up and
    /// releasing event as a 'double click'
    /// </summary>
    public TimeSpan TripleClickThreshold { get; set; }

    /// <summary>
    /// How far between a mouse down and mouse up before it is considered a 'drag' rather
    /// than a 'click'. Console row counts for 2 units while column counts for only 1. Distance is
    /// measured in Euclidean distance.
    /// </summary>
    public double DragThreshold { get; set; }

    public MouseState CurrentState { get; private set; }

    private ButtonNarrative? [] _ongoingNarratives = new ButtonNarrative? [4];

    public MouseStateManager (
        Func<DateTime>? now = null,
        TimeSpan? doubleClickThreshold = null,
        TimeSpan? tripleClickThreshold = null,
        int dragThreshold = 5
    )
    {
        Now = now ?? (() => DateTime.Now);
        DoubleClickThreshold = doubleClickThreshold ?? TimeSpan.FromMilliseconds (500);
        TripleClickThreshold = tripleClickThreshold ?? TimeSpan.FromMilliseconds (1000);
        DragThreshold = dragThreshold;
    }


    /// <summary>
    /// 
    /// </summary>
    /// <param name="e"></param>
    /// <returns></returns>
    public IEnumerable<ButtonNarrative> UpdateState (MouseEventArgs e)
    {
        // TODO: manage transitions

        for (int i = 0; i < 4; i++)
        {
           // Update narratives

           // Release stale or naturally complete ones based on thresholds
        }
    }

    /// <summary>
    /// If user double clicks and we are waiting for a triple click
    /// we should give up after a short time and just assume no more
    /// clicks are coming. Call this method if the state for a given button
    /// has not changed in a while.
    /// </summary>
    /// <returns></returns>
    public ButtonNarrative? ReleaseState (int button)
    {
        
    }

    private void PromoteSingleToDoubleClick ()
    {

    }
    private void PromoteDoubleToTripleClick ()
    {

    }

    public static double DistanceTo (Point p1, Point p2)
    {
        int deltaX = p2.X - p1.X;
        int deltaY = p2.Y - p1.Y;
        return Math.Sqrt (deltaX * deltaX + deltaY * deltaY);
    }
}

/// <summary>
/// Describes a completed narrative e.g. 'user triple clicked'.
/// </summary>
/// <remarks>Internally we can have a double click narrative that becomes
/// a triple click narrative. But we will not release both i.e. we don't say
/// user clicked then user double-clicked then user triple clicked</remarks>
public class ButtonNarrative
{
    public int Button { get; set; }
    public int NumberOfClicks { get; set; }

    /// <summary>
    /// Mouse states during which click was generated.
    /// N = 2x<see cref="NumberOfClicks"/>
    /// </summary>
    public List<ButtonState> MouseStates { get; set; }

    /// <summary>
    /// <see langword="true"/> if distance between first mouse down and all
    /// subsequent events is greater than a given threshold.
    /// </summary>
    public bool IsDrag { get; set; }
}

public class MouseState
{
    public ButtonState[] ButtonStates = new ButtonState? [4];

    public Point Position;
}

public class ButtonState
{
    /// <summary>
    ///     When the button entered its current state.
    /// </summary>
    public DateTime At { get; set; }

    /// <summary>
    /// <see langword="true"/> if the button is currently down
    /// </summary>
    private bool Depressed { get; set; }

    /// <summary>
    /// The screen location when the mouse button entered its current state
    /// (became depressed or was released)
    /// </summary>
    public Point Position { get; set; }

    /// <summary>
    /// The <see cref="View"/> (if any) that was at the <see cref="Position"/>
    /// when the button entered its current state.
    /// </summary>
    public View? View { get; set; }

    /// <summary>
    /// True if shift was provided by the console at the time the mouse
    ///  button entered its current state.
    /// </summary>
    public bool Shift { get; set; }

    /// <summary>
    /// True if control was provided by the console at the time the mouse
    /// button entered its current state.
    /// </summary>
    public bool Ctrl { get; set; }

    /// <summary>
    /// True if alt was held down at the time the mouse
    /// button entered its current state.
    /// </summary>
    public bool Alt { get; set; }
}
```

2024-11-26 02:51 UTC, tig commented
> Working on it but I think this is how I want to handle mouse.

Wow. I think I really like this!!

Can you write a paragraph that would go in the intro of `mouse.md` that describes the overall model in plain English, using the word "narrative"? This will go a long way to helping me understand your intent, and helping ensure your thinking is clear.

2024-12-07 11:59 UTC, tznind commented
I've updated the initial post with the new diagram of how `IApplication` fits in.  Theres a lot of work to knit things together to work robustly.  Theres just so much complexity in the existing code!

2024-12-08 10:29 UTC, tznind commented
Invoke, Idle and Timeout support in v2.

I refactored into a new class with interface `ITimedEvents` that is decoupled from main loop.

Currently still same code implementation but in future we can work on it seperately from main loop.

![v2-animation](https://github.com/user-attachments/assets/a70054d3-de50-4fd4-8947-58005cf14e78)
_Animation running in v2 with timed events, note the exit code 0, indicating we can also exit the app!_

2024-12-08 20:40 UTC, tznind commented
@BDisp I am struggling to figure out this bug I have with the new `WindowsOutput`

It seems to render correctly to the screen but then clear again immediately or something.

You can see by uncommenting the line:

```
                // Uncomment this to see that it does render properly :/
                // Process.GetCurrentProcess ().Kill();
```

I can't figure out what is clearing it or making the terminal not show - do you have any ideas?

![console-no-show](https://github.com/user-attachments/assets/f7cee31e-6427-446c-bd69-82d4377a384d)

It was working correctly in a small test project, and the NetDriver style NetOutput works correctly (you can change to net driver by doing following):

```diff
-        if ( p == PlatformID.Win32NT || p == PlatformID.Win32S || p == PlatformID.Win32Windows)
-        {
-            var inputBuffer = new ConcurrentQueue<WindowsConsole.InputRecord> ();
-            var loop = new MainLoop<WindowsConsole.InputRecord> ();
-            _coordinator = new MainLoopCoordinator<WindowsConsole.InputRecord> (TimedEvents,
-                                                                                () => new WindowsInput (),
-                                                                                inputBuffer,
-                                                                                new WindowsInputProcessor (inputBuffer),
-                                                                                () => new WindowsOutput (),
-                                                                                loop);
-        }
-        else
-        {
            var inputBuffer = new ConcurrentQueue<ConsoleKeyInfo> ();
            var loop = new MainLoop<ConsoleKeyInfo> ();
            _coordinator = new MainLoopCoordinator<ConsoleKeyInfo> (TimedEvents,
                                                                    () => new NetInput (),
                                                                   inputBuffer,
                                                                   new NetInputProcessor (inputBuffer),
                                                                   () => new NetOutput (),
                                                                   loop);
-        }
```

Any help would be greatly appreciated

2024-12-09 01:47 UTC, BDisp commented
Sorry I couldn't found the cause of this issue. My laptop overheat running it. I thought the cause was due to the recursive write which doesn't allow the driver show the output, but enabling the conditional `if (s != _lastWrite)` it still doesn't output anything. I also add this conditional to avoid always clear the contents, but still remain the issue.

```cs
        if (OutputBuffer.Cols != size.Width || OutputBuffer.Rows != size.Height)
        {
            OutputBuffer.SetWindowSize (size.Width, size.Height);
        }
```

You have to see when this issue started happening to check the commit that cause it.

2024-12-09 07:43 UTC, tznind commented
Found one issue,  `WindowsConsole` which I thought was just helper functions - it actually spins up an infinite loop of its own to read console input with no delay.

I have turned it off based on bool to constructor and now you can at least boot and Esc to exit WindowsDriver and see the output! But still there is the issue of clearing even if you change the wait period to 500ms etc. 

One of the tenants of v2 is to prevent any view refreshing, pushing output, clearing screen etc ever.

Instead the view has to notify its intent e.g. via SetNeedsDisplay and then MainLoop<T> (the new loop) does it once at the end of the iteration.

9a72628d354fbc419086ba8232e987b648f60479

2024-12-09 08:28 UTC, tznind commented
Maybe the output is being written to one screen buffer but app has switched to another and it only comes back on exit the app?

2024-12-09 09:27 UTC, BDisp commented
Maybe it's using a different output handle than the original.

2024-12-09 13:12 UTC, BDisp commented
> I have WindowsOutput on one thread and WindowsInput on a different one, perhaps the output is writing to the buffer that the input one is using while also creating its own or something.

Output and input handles are separated from each other. You make ensures recreating the handles after shutdown and not during. Make sure the handles isn't changed during a normal iteration.

2024-12-11 20:39 UTC, tznind commented
Windows Output driver working :) I stopped using WindowsConsole and just copied relevant methods across to WindowsOutput instead.  I think issue was wrong handle.

2024-12-14 11:36 UTC, tznind commented
@tig how far are we along the route of making it so MenuBar and StatusBar are not 'special views' that sit outside of the hierarchy (i.e. outside of Application.Top).

I am trying to get the new main loop to work as follows:

- Nobody is allowed to 'ad hoc draw' i.e. Driver.Refresh does nothing
- Exclusively operate on NeedsDisplay / NeedsLayout
- Draw only once at the end of the main loop and only if views need it

Currently this results in menu/status bar disapearing.  This is the current 'brute force' draw approach:

```csharp
 public void Iteration ()
 {
     InputProcessor.ProcessQueue ();

     if (Application.Top != null)
     {
         bool needsDrawOrLayout = AnySubviewsNeedDrawn(Application.Top);

         if (needsDrawOrLayout)
         {
             // TODO: throttle this
             var size = Out.GetWindowSize ();

             OutputBuffer.SetWindowSize (size.Width, size.Height);

             // TODO: Test only

             Application.Top.Layout ();
             Application.Top.Draw ();

             Out.Write (OutputBuffer);
         }
     }

     TimedEvents.LockAndRunTimers ();

     TimedEvents.LockAndRunIdles ();
 }

 private bool AnySubviewsNeedDrawn (View v)
 {
     if (v.NeedsDraw || v.NeedsLayout)
     {
         return true;
     }

     foreach(var subview in v.Subviews )
     {
         if (AnySubviewsNeedDrawn (subview))
         {
             return true;
         }
     }

     return false;
 }
```

2024-12-15 15:02 UTC, tznind commented
Ok most stuff works and cpu sits at about 0% 

Now needs loads of tests and to round out a few implementations like all the various key translations, double click etc

I think I will add ILogger support so we can see things like ignored ansi codes, record where/if there is slowdown etc

2024-12-16 17:11 UTC, BDisp commented on Terminal.Gui/ConsoleDrivers/V2/NetInputProcessor.cs
> +        var key = EscSeqUtils.MapKey (input);
Good choice.

2024-12-19 07:52 UTC, tznind commented
Ok I need to work a bit on my understanding of how to integrate `Application.Run`.

The users main entry thread for `Program.cs` is going to call `Application.Init` and then `Run`.

That method will 'block' but it also is the thread that processes Click events e.g. if the user wants to `Run` another `View`.

Currently I have 2 main threads
- Input Loop
- Everything else loop (output, timers, layout, draw etc)

But I'm realizing now that that is an issue for integrating with `Run`.  Because `Run` has to appear to block but still process user event code (e.g. click) and be able to put another `Run` call onto the csharp call stack.

Any insight into my understanding of things or suggestions would be welcome - especially clarifications on how it is currently working as its a bit opaque.

This is my vision for how v2 will work.  At the moment Run just blocks and loops, looking at the state of the coordinator.  But that does not work well for starting a nested Run or exiting a nested Run back into the parent Run.

![image](https://github.com/user-attachments/assets/20029961-7776-4a77-8ab4-0e4ee314c104)

2024-12-20 19:51 UTC, tznind commented
Ok I have got it! Looking at the existing codebase the 'Iterate/Output' loop that I have on its own thread is actually called repeatedly within `Run`.  This means that the entry thread the application has in their program is the one that the UI code is all running on.

That makes sense and is 1 less thread so I'm up for it.  Now you can open and close as many scenarios as you want.

2024-12-26 18:20 UTC, tznind commented
Have started looking at logging (using defacto standard `System.Extensions.Logging`).  I've used Serilog for UICatalog but any logging framework will be compatible in end users applications. It would be nice to throw if user tries to set a console logger but probably impractical to do reliably.

For metrics I'm less certain on the 'standard' approach.  After a couple of false starts I found the [Meter class in System.Diagnostics.Metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation) which seems to be a good fit for performance logging:

To see metrics realtime for running process you can run:
```
dotnet tool update -g dotnet-counters
dotnet-counters monitor -n UICatalog --counters Terminal.Gui
```

![image](https://github.com/user-attachments/assets/e6212162-d526-458e-a2d0-32ea91c21764)
_File logging in client program UICatalog using Serilog dependency + metrics monitoring via `dotnet-counters`_

2024-12-28 14:53 UTC, tznind commented
I have dialed MouseInterpreter way back to just do the existing click behaviours including repeat click.  It was getting too complicated and it doesnt actually make sense to delay reporting click to see if there is double click - so it is back to reporting click,double then triple.

2024-12-28 20:36 UTC, tznind commented
Ok this is notionally ready for first pass review

I'm onto the final phase now

- [ ] Warnings (NRT, xmldoc etc)
- [ ] Unit tests
- [ ] All the corner cases I'm forgetting about

You can run with:
![image](https://github.com/user-attachments/assets/065a25df-1d02-40ae-90d9-8b6701e9c425)

2024-12-29 19:42 UTC, tznind commented
Once this is merged and well tested we can have an epic deleting session to remove the old drivers - if we want to that is.

2024-12-31 15:49 UTC, tznind commented
@BDisp can you see if you can see why right click context menus are not popping? I guess something about the mouse event(s) in v1 vs v2?

2025-01-01 19:03 UTC, BDisp commented
> ok looks like Released+Clicked flags together is bad. TG code wants 2 seperate events I think.
> 
> Got it, is just about order of events

Glad you found the solution but that's really the cause of the bad behavior that was causing the right click wasn't working. Of course that each escape sequence must raise separate events, for them to work as expected. Good work and Happy New Year.

2025-01-01 19:23 UTC, tznind commented
>  Of course that each escape sequence must raise separate events, for them to work as expected. Good work and Happy New Year.

Happy new year! 

There is actually no escape sequence for click so you must in fact create one manually in interpreter:

Input:
```
[<0;3;3m
[<35;3;3m
[<0;4;4M
```
We see mouse is moved with no button
Mouse is down (button 35)
Mouse is released (button is back to 0 - also we have 'M' instead of 'm;)

This must currently be translated into 4 events for Terminal.Gui right click menu to work properly:
```
ReportMousePosition
Button1Pressed
Button1Released
Button1Clicked
```

So it is not a 1 to 1 mapping between escape codes and events, click is a 'supplemental' event that we inject into the event stream.

Combining flags e.g. Released+Click as one event does not work with current codebase (which is the original thing I was doing).

2025-01-01 20:49 UTC, tznind commented
@BDisp `EscSeqUtils.MapKey` does not handle backspace.  Here is the ConsoleKeyInfo that comes in direct from console when reading with console read:

![image](https://github.com/user-attachments/assets/74bd2225-43b2-4c99-9412-d4c28ff3ee6f)

Apparently:
> When you press the Backspace key, the console might interpret it as sending the 127 (0x7F) code instead of 0x08 (Backspace).
> This happens because of differences in how the terminal emulator or console environment maps keyboard keys to control codes.

How is this handled in NetDriver? is MapKey the best place to put this new logic?

2025-01-01 21:05 UTC, BDisp commented
The `DEL` (127) is handled on the `EscSeqUtils.MapConsoleKeyInfo` method.

![image](https://github.com/user-attachments/assets/423f8762-cdea-47d3-892b-f0cef9e45148)

2025-01-01 22:42 UTC, BDisp commented
This code fixes the right button click to popup the context menu.

![image](https://github.com/user-attachments/assets/d54bb847-e860-487e-b211-a914ba65a17b)

2025-01-02 07:24 UTC, tznind commented
> The DEL (127) is handled on the EscSeqUtils.MapConsoleKeyInfo method.

Great, I have added in call to this function in the new architecture, see [aa8bdd7](https://github.com/gui-cs/Terminal.Gui/pull/3837/commits/aa8bdd72499f7a95e75485acefe07eef0a3c6642)

> This code fixes the right button click to popup the context menu.

Right click works for v2 net but not v2 win, I will have to explore your suggestion further when I have some time.

2025-01-02 07:36 UTC, tznind commented
Windows right click working thanks! [6c55e11](https://github.com/gui-cs/Terminal.Gui/pull/3837/commits/6c55e117e015c15614b5fa1e902968a7182b3800)

2025-01-02 12:13 UTC, BDisp commented
> Great, I have added in call to this function in the new architecture, see [aa8bdd7](https://github.com/gui-cs/Terminal.Gui/pull/3837/commits/aa8bdd72499f7a95e75485acefe07eef0a3c6642)

Nice.

> Right click works for v2 net but not v2 win, I will have to explore your suggestion further when I have some time.

Works with `NetDriver` because it rely in the `EscSeqUtils` API and `WindowsDriver` don't, and it's needed to point the right way how to handle it. Don't forget to deal with the warning.

2025-01-11 15:54 UTC, tznind commented
I have added metrics for Redraw in v2 drivers and Trace logging for the view that is responsible for wanting itself redrawn.  This will let us fix issues e.g. this one where HexView is constantly saying it wants layout and redraw when nothing is going on in app:

![image](https://github.com/user-attachments/assets/e75e70fc-a86d-4c0f-968e-4b9b08aacd0a)

2025-01-14 19:51 UTC, tznind commented
@BDisp @tig any feedback on this PR would be appreciated.

2025-01-14 20:07 UTC, BDisp commented
> @BDisp @tig any feedback on this PR would be appreciated.

I'm in vacancy mode sorry.

2025-01-15 14:00 UTC, tig commented
> @BDisp @tig any feedback on this PR would be appreciated.

Yes. 

My lighthouse beam is focused on other things right now. 

But it's swinging around and will be back on TG real soon now. 

I'm really excited about this PR!

2025-01-18 09:38 UTC, tznind commented
@BDisp the ` EscSeqUtils.MapConsoleKeyInfo` is broken for some keys e.g. 

```
new ConsoleKeyInfo ('}', ConsoleKey.Oem6, true, false, false), new Rune ('}') 
```
Gets returned as 
```
new ConsoleKeyInfo('}', ConsoleKey.None, true, false, false);
```

This then breaks `EscSeqUtils.MapKey` 

`MapConsoleKeyInfo` and `MapKey` are the two methods I am chaining to turn `ConsoleKeyInfo` into `Key`

For now I am using workaround:

```csharp
 /// <summary>
 /// Converts terminal raw input class <see cref="ConsoleKeyInfo"/> into
 /// common Terminal.Gui event model for keypresses (<see cref="Key"/>)
 /// </summary>
 /// <param name="input"></param>
 /// <returns></returns>
 public static Key ConsoleKeyInfoToKey (ConsoleKeyInfo input)
 {
     ConsoleKeyInfo adjustedInput = EscSeqUtils.MapConsoleKeyInfo (input);
     
     // TODO : EscSeqUtils.MapConsoleKeyInfo is wrong for e.g. '{' - it winds up clearing the Key
     //        So if the method nuked it then we should just work with the original.
     if (adjustedInput.Key == ConsoleKey.None && input.Key != ConsoleKey.None)
     {
         return EscSeqUtils.MapKey (input);
     }

     return EscSeqUtils.MapKey (adjustedInput);
 }
```

2025-01-29 22:32 UTC, tig commented
Starting my review...

Some things I noticed in pulling down and running locally. This is with "ConsoleDriverFacade(win)"

* Incorrect drawing:
![image](https://github.com/user-attachments/assets/f9430893-1cb2-4cef-896d-42c35c58053f)

* Window drag doesn't work
* App hotkeys don't work (Ctrl-A) for UI Catalog about box.
* Exiting UI Catalog about box causes an exception

This stuff leads me to believe this isn't really ready for merge, right? 

But you want me to review the code?

2025-01-29 22:34 UTC, tig commented
Running UICatalog "All Views Tester" -b -t 5000 --driver v2net

Shows lots of issues.

2025-01-29 22:55 UTC, tig requested changes
Some comments here. 

My review was pretty superficial. I didn't actually dive deep into the tests.

What is your thinking on how we move forward with this?

It appears that unless you explicitly enable the new drivers, everything works swell.

Is the intent to merge with the new drivers "broken" and then fix them off of v2_develop?

2025-01-29 22:55 UTC, tig commented on Terminal.Gui/ConsoleDrivers/V2/ApplicationV2.cs
> +    private readonly Func<INetInput> _netInputFactory;
Not sure I like having Application be so tightly bound to "net" and "win". What about curses/linux? Or is the idea "net" works great on linux?

2025-01-29 22:55 UTC, tig commented on Terminal.Gui/ConsoleDrivers/V2/Logging.cs
> +public static class Logging
Love this concept. 

Does it have to be restricted to drivers though?

2025-01-30 01:28 UTC, tznind commented on Terminal.Gui/ConsoleDrivers/V2/ApplicationV2.cs
> +    private readonly Func<INetInput> _netInputFactory;
Yes my current thinking is that if we can get away with only the two drivers then it will make things simpler.

I think core dotnet console apis will work fast and well enough now on Linux for prime time - but we can test and see if there are distros that have performance issues that would need curses.

Application is the ugliest bit of this PR as it is where the old architectural approach (static gateway + driver monolith) meets the new (orchestrator + generics subcomponents).

I think these factories and how we boot strap new architecture will evolve here.

This needs to be good enough not perfect (my hope anyway).

2025-01-30 01:35 UTC, tznind commented on Terminal.Gui/ConsoleDrivers/V2/Logging.cs
> +public static class Logging
Certainly this can be used later on for other bits of the core code, it is not tied to drivers specifically.

2025-01-30 01:43 UTC, tznind commented
I would like to fix bugs.  Especially any crash bugs.

Biggest issue I noticed was with menus.  They seem to be 'special case' for Top and have explicit code in Application that interacts with them.  

I was hoping that if we could get it so any view can have menus and they work just like any other subview - then the issues might become less opaque and/or disappear. 

Let me try the all views tester.  I have run many scenarios in isolation but it's unclear what some of them are meant to do upon cursory examinations.

It would be great to have help identifying the main outstanding 'show stopper bugs' in terms of behaviour.

2025-01-30 01:56 UTC, tznind commented
I want to solve all the 'driver level' bugs but then address 'view specific' issues later e.g. HexView always reporting that it NeedsLayout/NeedsRedraw constantly true. 

The new 'main loop' is more trusting of the views reporting their state. 

For example there are no longer any 'out of band' screen Refresh allowed. Console is only flushed/updated after loop iteration and only once (and only if a View was needs draw true)

2025-01-30 07:21 UTC, tznind commented on Terminal.Gui/ConsoleDrivers/V2/Logging.cs
> +public static class Logging
I only put it in this Drivers folder because its where I was creating everything else, can move to root or another folder if you like.

2025-01-30 08:07 UTC, tznind commented
> Running UICatalog "All Views Tester" -b -t 5000 --driver v2net

I've not used this before,  I will have a look into it thanks.

I also see that the behaviour of app is different when launch  from UICatalog vs visual studio e.g. black colors.  Maybe something to do with configuration file/paths

![image](https://github.com/user-attachments/assets/f953f83c-cfc0-4064-aeae-bebeeb51d25c)

2025-01-30 18:48 UTC, tznind commented
Looks like AllView tester is double booting.  And the LayoutEditor is constantly reporting true for redraw.

```
2025-01-30 18:40:02.825 +00:00 [INF] Main Loop Coordinator booting...
2025-01-30 18:40:02.842 +00:00 [INF] Creating NetOutput
2025-01-30 18:40:02.844 +00:00 [INF] Creating NetInput
2025-01-30 18:40:02.846 +00:00 [INF] Main Loop Coordinator booting complete
2025-01-30 18:40:02.849 +00:00 [INF] Main Loop Coordinator booting...
2025-01-30 18:40:02.849 +00:00 [INF] Creating NetOutput
2025-01-30 18:40:02.849 +00:00 [INF] Creating NetInput
2025-01-30 18:40:02.849 +00:00 [INF] Main Loop Coordinator booting complete
2025-01-30 18:40:02.942 +00:00 [INF] Run 'Window(Esc to Quit - Scenario: All Views Tester){X=0,Y=0,Width=0,Height=0}'
2025-01-30 18:40:03.002 +00:00 [VRB] Window triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.003 +00:00 [INF] Console size changes from '{Width=0, Height=0}' to {Width=120, Height=30}
2025-01-30 18:40:03.128 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.184 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.247 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.309 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.372 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.434 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.498 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.561 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.625 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.688 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.751 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.813 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.877 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:03.940 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.003 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.067 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.129 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.191 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.255 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.318 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.379 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.442 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.505 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.568 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.631 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.691 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.753 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.814 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.875 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.938 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:04.999 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.061 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.124 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.186 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.248 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.311 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.373 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.436 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.498 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.552 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.607 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.670 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.732 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.794 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.857 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.919 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:05.983 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.045 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.108 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.171 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.233 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.296 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.358 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.420 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.483 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.545 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.608 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.669 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.732 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.793 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.855 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.918 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:06.981 +00:00 [VRB] AnsiResponseParser releasing ''
2025-01-30 18:40:06.984 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:07.043 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:07.106 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:07.170 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:07.233 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:07.295 +00:00 [VRB] LayoutEditor triggered redraw (NeedsDraw=True NeedsLayout=True) 
2025-01-30 18:40:07.358 +00:00 [VRB] Layou [...]

2025-01-30 20:44 UTC, tig commented
> I would like to fix bugs.  Especially any crash bugs.
> 
> Biggest issue I noticed was with menus.  They seem to be 'special case' for Top and have explicit code in Application that interacts with them.  

Hence the Issues and PRs around Top and rewriting Menu. See those. 

> 
> I was hoping that if we could get it so any view can have menus and they work just like any other subview - then the issues might become less opaque and/or disappear. 

Yes. See related menu PRs.

2025-01-31 08:05 UTC, tznind commented
All views tester now working, was just missing raising init event.  Looks like configuration manager doesnt work same either as its monochrome - I will look into this
![allviews](https://github.com/user-attachments/assets/fc199137-7384-4116-8a38-a01152c3690e)

```
dotnet run -- "All Views Tester" -b -t 5000 --driver v2nwin
```

![allviews](https://github.com/user-attachments/assets/fc199137-7384-4116-8a38-a01152c3690e)

2025-01-31 08:42 UTC, tznind commented
Colors fixed, I just wasn't calling the init on config manager from the new bootstrapping Application2 class init

2025-02-02 20:46 UTC, BDisp commented on Terminal.Gui/ConsoleDrivers/V2/MainLoop.cs
> +        //       until you click.  This should not be the job of the main loop!
You're right. That must be an `Application` job.

2025-02-02 20:56 UTC, tznind commented on Terminal.Gui/ConsoleDrivers/V2/MainLoop.cs
> +        //       until you click.  This should not be the job of the main loop!
Somehow, it seems to work with the original drivers but not the v2 ones.

V2 drivers only listen to these properties (needs layout/draw).  There are no manual or triggered draws, so possibly that is why this hack is needed for now.

2025-02-02 21:11 UTC, BDisp commented on Terminal.Gui/ConsoleDrivers/V2/MainLoop.cs
> +        //       until you click.  This should not be the job of the main loop!
I understand, but I think that if you do the same thing in the `Application.LayoutAndDraw` method you'll will obtain the same result, but I could be wrong.

2025-02-02 21:22 UTC, tznind commented on Terminal.Gui/ConsoleDrivers/V2/MainLoop.cs
> +        //       until you click.  This should not be the job of the main loop!
In my code, layout and draw is only called if a subview of Top wants redrawn or layed out... I will look into it some more later

2025-02-05 20:34 UTC, tznind commented
I think the remaining issues are to do with layout and/or the new iteration.

I am trying to structure the new MainLoop<T> to only redraw and/or layout when a view says it needs to.  I think implementation is quite naive but I also think the existing main loop/application is quite brittle and exposed e.g. anyone can and does call Refresh, Layout etc at will.

I could use some help, for example I see lots of LayoutException that get caught later on.  Why does that happen with new loop and not old? It's hard to understand why.

2025-02-08 10:09 UTC, tznind commented
@tig my proposal for this branch would be to confirm

- Regular drivers are not broken (confirmed)
- Issues with the new drivers are primarily small and/or layout/redraw related

Then we can merge it and I can do a followup work where we log the hell out of everything in the library and I can start working on layout/draw issues.

2025-02-12 14:46 UTC, tig commented
Travelling and had a few minutes to play.... This is looking great. 

I agree with your plan for mergeing...

Some new issues I noticed:

Line Drawing pallette is corrupt.

![](https://i.imgur.com/ltnlc5K.png)

Drag about box window broken (and crashes) on .win driver.

![W0LJM3E 1](https://github.com/user-attachments/assets/7c1332f0-f00b-4e78-b452-8be0383def94)

Drag scroll bar sometimes doesn't restore non-drag color:

![8anNNx5 1](https://github.com/user-attachments/assets/62bbb164-fe0b-450f-b784-96e8cf7d4eaf)

Numeric up/down does not auto-increment/acellerate when held.

Charmap has a bunch of issues. Getting CP info never completes. When loaded, the right hand pane doesn't show until a mouse move. 

![image](https://github.com/user-attachments/assets/eb26d0f5-6d25-48fc-af5e-88aabe45f10c)

2025-02-12 19:25 UTC, tznind commented
Good finds! seems I was not raising released flags on win driver.  [cc96920](https://github.com/gui-cs/Terminal.Gui/pull/3837/commits/cc96920cc308df12101015d7bce716e986a5dbdf) shoulf fix the 'mouse grab' related bugs (drag window etc)

2025-02-13 19:36 UTC, tznind commented
> Line Drawing pallette is corrupt.

Initial size is corrupt, if you drag out the bottom and right it appears as it does in normal drivers.  The checker pattern for background color is normal.  Though I note that background colour doesnt work in any of the drivers - seems like a regression, I remember it used to work.

> When loaded, the right hand pane doesn't show until a mouse move.

Hmn probably it doesn't properly implement NeedsDisplay or part of its layout doesn't trigger it.  I think there will quite a bit of this, we need to have things like view becoming visible for first time to set it as NeedsDisplay.  The old architecture had a lot more `Refresh` and so on (`Refresh` is now completely ignored - all views must play nice with the loop and the NeedsDisplay / NeedsLayout flags).

2025-02-13 20:33 UTC, tznind commented
Have fixed the Ready event not being raised in [6b9367f](https://github.com/gui-cs/Terminal.Gui/pull/3837/commits/6b9367f0a4e6626726a6af1c89f63bca541acdca).

2025-02-27 17:28 UTC, tig requested changes
Looking great! Just a few asks...

2025-02-27 17:28 UTC, tig commented on Terminal.Gui/ConsoleDrivers/AnsiResponseParser/AnsiResponseParser.cs
> +    public event Action<object, Key>? Keyboard;
Why Action? I thought we agreed on this model for events in the library?

https://gui-cs.github.io/Terminal.GuiV2Docs/docs/events.html

Specifically:

> Common Patterns
> The primary pattern for events is the event/EventHandler idiom. We use the Action<T> idiom > sparingly. We support INotifyPropertyChanged in cases where data binding is relevant.

Happy to be educated on why Action is better here.

2025-02-27 17:28 UTC, tig commented on Terminal.Gui/ConsoleDrivers/V2/InputProcessor.cs
> +    public IKeyConverter<T> KeyConverter { get; }
missing API docs?

2025-02-27 19:48 UTC, tznind commented on Terminal.Gui/ConsoleDrivers/AnsiResponseParser/AnsiResponseParser.cs
> +    public event Action<object, Key>? Keyboard;
Just an oversight, have fixed 🚀

2025-02-28 02:56 UTC, tznind commented
Merge conflict fixed

2025-02-28 03:56 UTC, tig approved these changes

2025-02-28 15:26 UTC, tig commented
I want to merge this, but we keep getting unit test failures (see https://github.com/gui-cs/Terminal.Gui/issues/3930).

likely not due to this PR, but I'm not going to merge until this passes at least once. I just restarted the action....

2025-02-28 19:09 UTC, merged