Fixes #3836. SetupFakeDriver sometimes causes failure in the unit test.
gui-cs/Terminal.Gui pull request #3879
Opened 2024-12-03 22:40 UTC by BDisp

## Fixes

- Fixes #3836

## Proposed Changes/Todos

- [x] `Application.Screen` was causing this issue because `_screen` wasn't being set to null after running a test using the `SetupFakeDriver`.

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

2024-12-03 22:51 UTC, BDisp commented
This error doesn't happens all the time. It's a racing condition when a unit test that use the `SetupFakeDriver` after it's finished and another unit test that doesn't use it start and will call the `superView.SetRelativeLayout (new (10, 10));` when the `Application.Screen` was already be set to that size before in the first unit test.

2024-12-05 15:49 UTC, tig requested changes

2024-12-05 15:49 UTC, tig commented on Terminal.Gui/Application/Application.Initialization.cs
> +        InitState ();
1) Please rename this to `SubscribeDriverEvents`
2) Move the call up to line 153 (just after the call to `Driver!.init()`)
3) Add another `internal` method `UnsubscribeDriverEvents` that does the `-=` and replace the code in `Application.cs` line 180 with a call to this new method.

2024-12-05 19:26 UTC, tig requested changes

2024-12-05 19:26 UTC, tig commented on Terminal.Gui/Application/Application.Initialization.cs
> +        Driver.SizeChanged -= Driver_SizeChanged;
Add `ArgumentNullException.ThrowIfNull (Driver);` here

2024-12-05 19:34 UTC, BDisp commented on Terminal.Gui/Application/Application.Initialization.cs
> +        Driver.SizeChanged -= Driver_SizeChanged;
Good catch. Done.

2024-12-05 20:16 UTC, tig approved these changes
Well done. Thanks.

2024-12-05 20:16 UTC, merged